[package]
name = "ceph-client"
version = "0.1.0"
authors = ["Chris MacNaughton <chris@centaurisolutions.nl>"]

[dependencies]
# ceph-rust = "0.1.17"
ceph-rust = { git="https://github.com/ceph/ceph-rust" }
error-chain = "0.11"